export const AuthActionType = {
    LOGGING_USER: "LOGGING_USER",
    LOGGING_USER_SUCCESSFULLY: "LOGGING_USER_SUCCESSFULLY",
    LOGGING_USER_ERROR: "LOGGING_USER_ERROR",
    LOGOUT_USER: "LOGOUT_USER"
}

export const UsersActionType = {
    FETCH_USERS: "FETCH_USERS",
    FETCH_USERS_SUCCESSFULLY: "FETCH_USERS_SUCCESSFULLY",
    FETCH_USERS_ERROR: "FETCH_USERS_ERROR",
    ADDING_USER: "ADDING_USER",
    ADDING_USER_SUCCESSFULLY: "ADDING_USER_SUCCESSFULLY",
    ADDING_USER_ERROR: "ADDING_USER_ERROR",
}