export const AuthActionType = {
    SET_USER: "SET_USER",
    UNSET_USER: "UNSET_USER",
};

export const UsersActionType = {
    SET_USERS: "SET_USERS",
    ADD_USER: "ADD_USER",
    REMOVE_USER: "REMOVE_USER",
    UPDATE_USER: "UPDATE_USER",
    SET_IS_USERS_LOADING: "SET_IS_USERS_LOADING",
    SET_USERS_ERROR: "SET_USERS_ERROR",
};

export const schedulesActionType = {
    SET_SCHEDULES: "SET_SCHEDULES",
    ADD_SCHEDULE: "ADD_SCHEDULE",
    REMOVE_SCHEDULE: "REMOVE_SCHEDULE",
    UPDATE_SCHEDULE: "UPDATE_SCHEDULE",
    SET_IS_SCHEDULES_LOADING: "SET_IS_SCHEDULES_LOADING",
    SET_SCHEDULES_ERROR: "SET_SCHEDULES_ERROR",
};

export const AppActionType = {
    SET_IS_LOADING: "SET_IS_LOADING",
    SET_ERROR: "SET_ERROR",
};